travis:
  secure:
    BINSTAR_TOKEN: ANeRxZdLJa5VrTohxuivVT2+lrQ2gQGycOBgZQuFDK5IqgRDGVCCvQXnKnTnSvxikQGi0jOT8Ll9neEx7mO4rV/2otCBieP1diUlePJrBWy/eSq16NLZoATCxB3bO/n4mkt6JsEftOCws7nqtETE9/8Kut6JED6MsjebRhjiWLRCLbR4FLEnEOKCUzUBASTXWZ7xmIsYRZMUQ+E+6Jb8imYAPzF9YdAB5TFIEl77z91c1m79JkT2xEzJH4nLWTPTyIyFhUVHRG71l9KOznA+CmKPorgyHT0xMtrHn4KuhgPEbinnzOKO+9g0lXymbelNlhshmzMDjX1hRSP+RO3ziG+zy4swoD85PgpJBLvOkiI5KBDc7i19p0G/OEv8adkbIGq7tDNlu+Rim6bmdCDZj5pT53YiyY3L7vYfLSTNrXbDFP3uI+XD4TRCXhcwIgjTDJgyoClgyYh+iVyLLTynzagrJKbKTsTESHZpQ9lUJXYl5onlpjbASxS+4JB4jM/V0hKCbtQ4zUswvuy1QCNFsp11pCyNztqqax6qppeV1tkSY1Tjjol9onuC3kQ6/cYjrhfasqjUGJ5AytgCqUHKJPvDghhjT4xO644iTlbp/t/Sphg3RRZUaQUuSQ0tcs6H/7tkCDVpu0P4ExTJ9oKYLgPLHirJ+FX0o6olp8rA66U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
