appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Sya7uLNyjvzXQYKSwGKQkSZ1iBNHUU7aMRudXA9TQk20RlzhfVtfqzscBDW6Z96eDjKjFe5dAY2LH8WAUvq+s+xculf6m1mEk1aCmf/euFrYSXH/ryC6vLfGORCHRu/4aVeEiCDk2QIYJhR7graQM9aScX8IbTirpdRfMHq4b8eVy7ey6fQD7QB0jbUJ+9RWnMXUxS7ry2sdfXR09eMINQssMXbke2VYS97SHyKRkCLOWNRB9qSrDqKDN70EUGa8Y/qquEEBkhqijSpEeVsW8hYvZGnXBw4wiMwZuUW7jE48V+DyYT7cmgA8q7Wf8ma9Y7f5Ljy0vUWULXKaudz6AJrYY54Z+HFKAfLum/GW5SePLd6PQKFw2MX/w7f4JCl4S2Cl4qItLxvEUbT7lY2Zm4GgHQJHcn0vWvr1XDc27J0HjERggo2KzODgeAx96omOdCWMwJFtVr95y7siLWGLJH3hWOsTXw6yQB9+CAtAwrqGV543vTrBPSnrzao1UYIdErnEI8kqdZgsF648ikdn1hzyUl7iapl0VvPwFHuR1TY2ibibqA2kS7tFIeQ+cWxpFtAFwxOyv9skTXwUdCntmo38P2mLFQIoI9ZmMC/EEKKsXcS9Ero/O+r/epVguCEIgFrcVE0mu0zp78h/ibawOudujdmUpvPMUujNM0+3rVU=}
conda_forge_output_validation: true
